name: Update Secrets

on:
  push:
    branches:
      - main

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update secrets in spoti2youtu.js
        run: |
          sed -i 's/MY_YOUTUBE_API_KEY/${{ secrets.YOUR_YOUTUBE_API_KEY }}/g' public/spoti2youtu.js
          sed -i 's/MY_SPOTIFY_CLIENT_ID/${{ secrets.YOUR_SPOTIFY_CLIENT_ID }}/g' public/spoti2youtu.js
          sed -i 's/MY_SPOTIFY_CLIENT_SECRET/${{ secrets.YOUR_SPOTIFY_CLIENT_SECRET }}/g' public/spoti2youtu.js
          sed -i 's/MY_SPOTIFY_REDIRECT_URI/${{ secrets.YOUR_SPOTIFY_REDIRECT_URI }}/g' public/spoti2youtu.js

